### ISSUE TITLE
Verifiability Question

### ISSUE THREAD

**Issue by ethanresnick** [paultopia/minitrue#1]
Maybe I'm missing something obvious...

Suppose I want to use minitrue to prove that document A was changed. Can't the publisher of document A simply claim that I modified my copy of A before tweeting the hash? In that case, iiuc, the old hash wouldn't match the hash of the currently-available document, and yet the publisher might have never changed the document.

Cool project, btw!

**Comment by paultopia** [comment]
Yes, that's a problem.  Date verifiability only protects against claims on the order of "you changed this document just now," not "you changed this document months ago."  But there really isn't a good solution to that one---except the hope that enough people use this or a similar tool that there is additional credibility conferred  bu multiple people having recorded the same prior document.

**Comment by paultopia** [comment]
(At least not a good solution I can think of!  If you have any ideas, please, let's do it!)

**Comment by ethanresnick** [comment]
> except the hope that enough people use this or a similar tool that there is additional credibility conferred bu multiple people having recorded the same prior document.

right, i think something like that is needed. Or, maybe it's not the number of people who've recorded the same prior document, but the credibility of those people, that matters. The problem, though, is that, if you need multiple/credible people, monitoring is no longer something that an individual can do on their own. At that point, i wonder if this is the right approach. Maybe, finding a way to (e.g.) trigger the internet archive to crawl a page, and then diffing those, would be better, assuming archive.org is trusted not to be tampered with.
